### ISSUE TITLE
navbar item styling

### ISSUE THREAD

**Issue by markup-mitchell** [codepoduk/website#10]
`#message-us` includes the `button` class, causing it to have a green background, but this is not consistent with the rest of the header styles and its purpose is unclear.

Trivial to remove this class if that is acceptable to the product owner.

**Comment by markup-mitchell** [comment]
@tomhuhges - in case you don't get alerted to new issues automatically!

**Comment by tomhuhges** [comment]
for some reason i didn't have notifications on so thanks!

its purpose was just to attract the eye to one of the menu items as a call to action. at the time of designing our priority was getting potential clients to message us, but that's no longer the case so feel free to remove - or add to meetups instead?
