### ISSUE TITLE
favicon not displaying in chrome tab

### ISSUE THREAD

**Issue by markup-mitchell** [codepoduk/website#11]
The codepod favicon displays correctly (ugly though it is) in my tab when accessed from my local clone. 

No favicon is visible in the production version of the site in Chrome or Firefox.

**Comment by tomhuhges** [comment]
needs moving inside the src folder and the link in index.html changed accordingly.

only the src folder is uploaded to surge, which is why it still works locally

**Comment by markup-mitchell** [comment]
Done. I've found favicon paths finicky in the past, so hope this works. Do you need to upload to surge manually after src is updated?

**Comment by tomhuhges** [comment]
nice one 👌🏻

yep, you can just do `npm run deploy` from the root folder as long as you have the surge cli installed (if not just do `npm install --global surge` beforehand)

**Comment by markup-mitchell** [comment]
OK, thanks. I'm not accepting my own PRs by the way, I'm treating you as the product owner. 
Think there needs to be some degree of control over that process!

**Comment by tomhuhges** [comment]
#12
